name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          python -m json.tool hacs.json > /dev/null
          python -m json.tool custom_components/dometic_cfx3/manifest.json > /dev/null
          python -m json.tool custom_components/dometic_cfx3/translations/de.json > /dev/null
          python -m json.tool custom_components/dometic_cfx3/translations/en.json > /dev/null
          python -m json.tool custom_components/dometic_cfx3/strings.json > /dev/null
