DOMAIN = "dometic_cfx3"
DEFAULT_PORT = 13142
DEFAULT_SCAN_NETWORK = "10.100.3.0/24"
DEFAULT_SCAN_TIMEOUT = 0.35
DEFAULT_SCAN_WORKERS = 64
DEFAULT_SCAN_INTERVAL = 60
CONF_SCAN_INTERVAL = "scan_interval"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_NAME = "name"
CONF_NETWORK = "network"
CONF_USE_SCAN = "use_scan"

TOPIC_CURRENT_TEMP = (0, 1, 1, 1)
TOPIC_TARGET_TEMP = (0, 2, 1, 1)
TOPIC_POWER = (0, 0, 3, 1)
TOPIC_BATTERY_VOLTAGE = (0, 1, 3, 1)
TOPIC_BATTERY_PROTECTION = (0, 2, 3, 1)
TOPIC_COMPRESSOR = (0, 3, 3, 1)
TOPIC_POWER_SOURCE = (0, 5, 3, 1)
TOPIC_NAME = (0, 0, 6, 1)

BATTERY_PROTECTION_OPTIONS = ["LOW", "MED", "HIGH"]
BATTERY_PROTECTION_TO_VALUE = {"LOW": 0, "MED": 1, "HIGH": 2}
VALUE_TO_BATTERY_PROTECTION = {0: "LOW", 1: "MED", 2: "HIGH"}
VALUE_TO_POWER_SOURCE = {0: "Netz (AC)", 1: "Batterie (DC)"}

ENTITY_PICTURE = "/local/dometic_cfx3_device.png"
